image:
  repository: ghcr.io/damienjburks/terraform-nuker
  tag: latest
  pullPolicy: Always

cronjob:
  schedule: "0 7 * * *"  # Daily at 2 AM America/Chicago (UTC-5)
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  backoffLimit: 2

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi
